/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'

declare let self: ServiceWorkerGlobalScope

cleanupOutdatedCaches()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Push Notification өңдеу
self.addEventListener('push', (event) => {
    if (!event.data) return

    try {
        const payload = event.data.json()
        const { title, body, icon, badge, data, actions, vibrate, requireInteraction } = payload

        const options: NotificationOptions = {
            body,
            icon: icon || '/images/icons.svg',
            badge: badge || '/images/badge.png',
            data: data || {},
            actions: actions || [],
            vibrate: vibrate || [100, 50, 100],
            requireInteraction: requireInteraction || false,
            timestamp: payload.timestamp || Date.now()
        }

        event.waitUntil(
            self.registration.showNotification(title, options)
        )
    } catch (e) {
        console.error('Push event error:', e)
    }
})

// Хабарламаны басқан кездегі әрекет
self.addEventListener('notificationclick', (event) => {
    const notification = event.notification
    const action = event.action
    const data = notification.data || {}

    notification.close()

    // Егер белгілі бір URL болса, соны ашу
    const urlToOpen = data.url || '/'

    event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // Егер браузерде бет ашық тұрса, соған ауысу
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i]
                if (client.url === urlToOpen && 'focus' in client) {
                    return client.focus()
                }
            }
            // Әйтпесе жаңа бет ашу
            if (self.clients.openWindow) {
                return self.clients.openWindow(urlToOpen)
            }
        })
    )
})
